import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ChartNoAxesCombined, Check, FileText, Files, Globe2, GraduationCap, MessageSquare, Settings, ShieldCheck, UserRound, UsersRound } from "lucide-react";

const services = [
  { id: "accounting-corporate-tax", icon: Files, title: "Accounting & Corporate Tax", description: "Accurate accounting and corporate tax solutions for businesses of all sizes.", detail: "Discuss your bookkeeping, financial reporting, and corporate tax needs with our team. We help you organize your finances and plan the next steps for your business." },
  { id: "personal-income-tax", icon: UserRound, title: "Personal Income Tax", description: "Simple, secure and maximized personal tax returns for individuals and families.", detail: "Get support with preparing and filing your personal return, understanding your tax documents, and identifying deductions and credits that may apply to your circumstances." },
  { id: "professional-training", icon: GraduationCap, title: "Professional Training", description: "Practical training programs to build financial literacy and professional skills.", detail: "Tell us your learning goals so we can discuss suitable training in financial literacy, accounting practices, and skills for professional development." },
  { id: "insurance-segregated-funds", icon: ShieldCheck, title: "Insurance & Segregated Funds", description: "Life insurance, investment solutions and wealth protection for a secure tomorrow.", detail: "Contact us to discuss your protection and long-term planning needs, available options, and the scope of support offered through this expanding service area." },
  { id: "consultancy-project-management", icon: ChartNoAxesCombined, title: "Consultancy & Project Management", description: "Strategic guidance for business growth, process improvement and project delivery.", detail: "We work with you to clarify objectives, review processes, and develop a practical plan for your project, with priorities and next steps tailored to your organization." },
  { id: "nonprofit-support", icon: UsersRound, title: "Not-for-Profit Support", description: "Specialized accounting and tax services for charities and non-profit organizations.", detail: "Discuss financial reporting, record keeping, and tax-related needs with a team that understands the importance of accountability and making resources count." },
  { id: "international-services", icon: Globe2, title: "International Services", description: "Supporting Canadian clients globally with cross-border tax and financial solutions.", detail: "Share the countries and financial matters involved in your situation. We will discuss your needs and the appropriate scope of cross-border support." },
];
const steps = [
  { icon: MessageSquare, title: "Understand Your Needs", description: "We listen to your goals and challenges." },
  { icon: FileText, title: "Plan & Strategize", description: "We design the right solution for you." },
  { icon: Settings, title: "Implement", description: "We put the plan into action." },
  { icon: ChartNoAxesCombined, title: "Deliver Results", description: "You achieve clarity, confidence and growth." },
];
const faqs = [
  { question: "What areas do you serve?", answer: "We serve clients across Canada and also support international clients with cross-border tax and financial services." },
  { question: "Do you work with small businesses?", answer: "Yes. We work with individuals, small businesses, growing enterprises, and nonprofit organizations, tailoring our support to their goals and needs." },
  { question: "How do I get started?", answer: "Contact us with a brief description of your needs and the service you are interested in. We will discuss your goals, answer your questions, and agree on the next steps." },
  { question: "Are your services confidential?", answer: "We treat your information with care. Before sharing sensitive financial documents, contact our team to confirm the appropriate secure method and discuss confidentiality requirements." },
  { question: "Do you offer virtual consultations?", answer: "Contact our team to arrange a consultation and discuss a remote meeting option that works for your location and schedule." },
];

export default function ServicesPage() {
  return (
    <main className="font-body text-[#0a213b] [&_h1]:font-serif [&_h1]:font-bold [&_h2]:font-serif [&_h2]:font-bold [&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h2]:text-[length:clamp(28px,_2.65vw,_40px)] [&_h2]:leading-[1.13] [&_h2]:tracking-[-.025em] [&_h3]:font-serif [&_h3]:font-bold [&_a:focus-visible]:[outline:3px_solid_#2c99ef] [&_a:focus-visible]:outline-offset-[5px] [&_summary:focus-visible]:[outline:3px_solid_#2c99ef] [&_summary:focus-visible]:outline-offset-[5px]">
      <section className="relative isolate overflow-hidden bg-[#021e39] text-[#fff] [&_h1]:mt-0 [&_h1]:mr-0 [&_h1]:mb-0 [&_h1]:ml-0 [&_h1]:text-[length:clamp(44px,_4.4vw,_65px)] [&_h1]:leading-[1.1] [&_h1]:tracking-[-.02em] [&_h1_span]:text-[#279fe9] max-[540px]:[&_h1]:text-[length:44px]" aria-labelledby="services-title">
        <Image src="/images/services/hero.png" alt="Fountain pen and financial reports on a modern office desk" fill sizes="100vw" preload className="z-[-2] object-cover object-center" />
        <div className="absolute z-[-1] top-0 right-[37%] bottom-0 left-0 [border-right:12px_solid_#82d0ff45] max-[800px]:top-0 max-[800px]:right-0 max-[800px]:bottom-0 max-[800px]:left-0 max-[800px]:[border:0] app-services-page-heroPanel [background-image:linear-gradient(110deg,_#001b36fc,_#002040f5)] [clip-path:polygon(0_0,_82%_0,_100%_100%,_0_100%)] [@media(max-width:_800px)]:[clip-path:none] [@media(max-width:_800px)]:[background-image:linear-gradient(90deg,_#001b34f5,_#001b34e0_60%,_#001b3470)]" aria-hidden="true" />
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-7 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-7.5 max-[540px]:pr-5 max-[540px]:pb-7.5 max-[540px]:pl-5">
          <nav aria-label="Breadcrumb" className="flex gap-y-3 gap-x-3 text-[#50b8f2] text-[length:15px] mb-6.25"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Our Services</span></nav>
          <div className="w-[55%] max-w-172.5 max-[800px]:w-[90%] max-[540px]:w-full">
            <h1 id="services-title">Our <span>Services</span></h1>
            <p className="text-[length:clamp(20px,_1.85vw,_28px)] leading-[1.35] mt-2.5 mr-0 mb-0 ml-0 max-[540px]:text-[length:20px]">Comprehensive Financial Solutions<br />for Individuals, Businesses and Organizations.</p>
            <span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" />
            <p className="text-[length:clamp(16px,_1.3vw,_19px)] leading-[1.55] mt-0 mr-0 mb-0 ml-0 max-w-162.5 max-[540px]:text-[length:16px]">At RD Prestige Services Corp., we deliver a full range of accounting, tax, insurance, training and consulting services to help you make confident financial decisions and achieve your goals.</p>
            <ul className={`grid grid-cols-3 list-none mt-6.25 mr-0 mb-0 ml-0 pt-0 pr-0 pb-0 pl-0 max-w-145 [&_li]:relative [&_li]:text-center [&_li]:text-[length:16px] [&_li]:leading-[1.3] [&_svg]:block [&_svg]:mt-0 [&_svg]:mr-auto [&_svg]:mb-2 [&_svg]:ml-auto [&_svg]:w-9.25 [&_svg]:h-9.25 [&_svg]:text-[#29a8ef] max-[540px]:[&_li]:text-[length:13px] max-[540px]:[&_svg]:w-7.75 max-[540px]:[&_svg]:h-7.75 app-services-page-trust [&_li_+_li::before]:[position:absolute] [&_li_+_li::before]:[left:0] [&_li_+_li::before]:[bottom:8px] [&_li_+_li::before]:[height:45%] [&_li_+_li::before]:[width:1px] [&_li_+_li::before]:[background:#2e9cd9] [&_li_+_li::before]:[content:""]`}><li><ShieldCheck aria-hidden="true" />Trusted<br />Expertise</li><li><UsersRound aria-hidden="true" />Client<br />Focused</li><li><ChartNoAxesCombined aria-hidden="true" />Real<br />Results</li></ul>
          </div>
        </div>
        <p className={`absolute top-11.25 right-[5%] text-[#143452] [font-family:"Segoe_Script",_cursive] text-[length:clamp(20px,_2vw,_29px)] italic leading-[1.2] [transform:rotate(-12deg)] max-[800px]:hidden app-services-page-heroSignature [&_.app-services-page-redLine]:[width:120px]`}>Your<br />Financial Partner<br />for a Brighter<br />Tomorrow<span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" /></p>
      </section>

      <section className="app-services-page-areas [background-image:linear-gradient(120deg,_#f4f9fd,_#f7fbfd)]" aria-labelledby="service-areas-title">
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container">
          <div className="flex items-center justify-between gap-y-10 gap-x-10 [&_>_div]:flex-[1.4] [&_>_p]:flex-1 [&_>_p]:max-w-125 [&_>_p]:text-[length:16px] [&_>_p]:leading-[1.5] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-3.75 [&_>_p]:ml-0 max-[800px]:flex-col max-[800px]:items-start max-[800px]:gap-y-0 max-[800px]:gap-x-0 max-[800px]:[&_>_p]:max-w-full max-[800px]:[&_>_p]:mb-6 app-services-page-sectionHeader"><div><p className="mt-0 mr-0 mb-3 ml-0 text-[length:12px] font-semibold leading-[1.5] tracking-[.2em] uppercase app-services-page-eyebrow">Our Service Areas</p><h2 id="service-areas-title">Services Designed Around Your Needs</h2><span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /></div><p>From tax preparation to financial planning, our integrated services help you save time, reduce risk, and unlock new opportunities.</p></div>
          <div className="grid grid-cols-4 gap-y-5 gap-x-5 [align-items:start] max-[1100px]:gap-y-4 max-[1100px]:gap-x-4 max-[800px]:grid-cols-2 max-[540px]:grid-cols-1">
            {services.map(({ id, icon: Icon, title, description, detail }) => (
              <article id={id} className="flex flex-col items-center min-h-85 pt-6 pr-6 pb-5.5 pl-6 rounded-[9px] bg-[#fff] shadow-[0_5px_16px_#153c6a09] text-center scroll-mt-28.75 [&_h3]:max-w-57.5 [&_h3]:min-h-13 [&_h3]:mt-4.5 [&_h3]:mr-0 [&_h3]:mb-3.25 [&_h3]:ml-0 [&_h3]:text-[length:clamp(20px,_1.6vw,_25px)] [&_h3]:leading-[1.1] [&_h3]:tracking-[-.02em] [&_>_p]:text-[#505e72] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-5 [&_>_p]:ml-0 [&_>_p]:text-[length:16px] [&_>_p]:leading-[1.5] max-[1100px]:pl-4 max-[1100px]:pr-4 max-[1100px]:min-h-87.5 max-[1100px]:[&_h3]:text-[length:20px] max-[1100px]:[&_>_p]:text-[length:15px] max-[800px]:min-h-82.5 max-[540px]:min-h-0 max-[540px]:pt-6.25 max-[540px]:pr-6.25 max-[540px]:pb-6.25 max-[540px]:pl-6.25 max-[540px]:[&_h3]:min-h-0 max-[540px]:[&_h3]:max-w-62.5 max-[540px]:[&_h3]:text-[length:24px] max-[540px]:[&_>_p]:text-[length:16px]" key={id}>
                <span className="grid place-items-center w-20.75 h-20.75 shrink-0 rounded-[50%] bg-[#eef5ff] text-[#006cdd] [&_svg]:w-11.5 [&_svg]:h-11.5 [&_svg]:[stroke-width:1.65]"><Icon aria-hidden="true" /></span><h3>{title}</h3><p>{description}</p>
                <details className="mt-auto w-full [&_summary]:inline-flex [&_summary]:items-center [&_summary]:justify-center [&_summary]:gap-y-1.5 [&_summary]:gap-x-1.5 [&_summary]:min-h-9 [&_summary]:text-[#0069df] [&_summary]:text-[length:15px] [&_summary]:font-semibold [&_summary]:cursor-pointer [&_summary]:list-none [&[open]_summary_>_svg]:[transform:rotate(-90deg)] [&_>_div]:[border-top:1px_solid_#e1eaf6] [&_>_div]:mt-2.5 [&_>_div]:pt-3.5 [&_>_div]:text-left [&_>_div_p]:text-[length:14px] [&_>_div_p]:leading-[1.55] [&_>_div_p]:text-[#526173] [&_>_div_p]:mt-0 [&_>_div_p]:mr-0 [&_>_div_p]:mb-3.75 [&_>_div_p]:ml-0 [&_>_div_a]:inline-flex [&_>_div_a]:items-center [&_>_div_a]:gap-y-1.5 [&_>_div_a]:gap-x-1.5 [&_>_div_a]:text-[#0065cf] [&_>_div_a]:text-[length:14px] app-services-page-serviceDetails [&_summary::-webkit-details-marker]:[display:none] [&[open]_.app-services-page-learnMore]:[display:none] [&[open]_.app-services-page-showLess]:[display:inline]"><summary><span className="app-services-page-learnMore">Learn More</span><span className="app-services-page-showLess [display:none]">Show Less</span><ArrowRight size={16} aria-hidden="true" /></summary><div><p>{detail}</p><Link href="/#contact">Discuss your needs <ArrowRight size={15} aria-hidden="true" /></Link></div></details>
              </article>
            ))}
            <aside className="relative isolate self-stretch overflow-hidden rounded-[9px] min-h-85 bg-[#dfedfa] [&_>_img]:z-[-1] [&_>_img]:object-cover [&_>_img]:object-[80%] [&_>_img]:opacity-[.45] [&_>_div]:pt-10 [&_>_div]:pr-6.25 [&_>_div]:pb-6 [&_>_div]:pl-6.25 [&_h3]:[border-left:4px_solid_#ff193b] [&_h3]:pl-5 [&_h3]:mt-5 [&_h3]:mr-0 [&_h3]:mb-5 [&_h3]:ml-0 [&_h3]:text-[length:clamp(29px,_2.7vw,_40px)] [&_h3]:leading-[1.06] max-[1100px]:[&_>_div]:pl-4.5 max-[1100px]:[&_>_div]:pr-4.5 max-[1100px]:[&_h3]:pl-3 max-[1100px]:[&_h3]:text-[length:30px] max-[540px]:min-h-75 max-[540px]:[&_>_div]:pt-7.5 max-[540px]:[&_>_div]:pr-7.5 max-[540px]:[&_>_div]:pb-7.5 max-[540px]:[&_>_div]:pl-7.5 max-[540px]:[&_h3]:text-[length:36px] app-services-page-partnerCard [&_.app-services-page-eyebrow]:[font-size:11px]">
              <Image src="/images/financial-future-background.png" alt="" fill sizes="(max-width: 600px) 100vw, 25vw" />
              <div><p className="mt-0 mr-0 mb-3 ml-0 text-[length:12px] font-semibold leading-[1.5] tracking-[.2em] uppercase app-services-page-eyebrow">More Than Services</p><h3>A Partner<br />in Your<br />Financial<br />Journey</h3><Link href="/#contact" className="inline-flex items-center justify-center gap-y-2.5 gap-x-2.5 min-h-11.25 pt-3 pr-6 pb-3 pl-6 rounded-[5px] text-[#fff] text-[length:14px] bg-[#006bcf] [transition:background_160ms_ease] hover:bg-[#004f9e] motion-reduce:[transition:none]">Get in Touch <ArrowRight size={17} aria-hidden="true" /></Link></div>
            </aside>
          </div>
        </div>
      </section>

      <section className="text-[#fff] app-services-page-process [background-image:linear-gradient(110deg,_#001b31,_#00203a,_#00182c)] [&_.app-services-page-sectionHeader_>_p]:[color:#e9f0fa] [&_.app-services-page-sectionHeader_>_p_span]:[color:#40b8f4]" aria-labelledby="process-title">
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container">
          <div className="flex items-center justify-between gap-y-10 gap-x-10 [&_>_div]:flex-[1.4] [&_>_p]:flex-1 [&_>_p]:max-w-125 [&_>_p]:text-[length:16px] [&_>_p]:leading-[1.5] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-3.75 [&_>_p]:ml-0 max-[800px]:flex-col max-[800px]:items-start max-[800px]:gap-y-0 max-[800px]:gap-x-0 max-[800px]:[&_>_p]:max-w-full max-[800px]:[&_>_p]:mb-6 app-services-page-sectionHeader"><div><h2 id="process-title">Our Process</h2><p className="mt-1.5 mr-0 mb-0 ml-0 text-[length:clamp(21px,_1.9vw,_28px)]">Simple. Transparent. Effective.</p><span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /></div><p>We follow a clear and collaborative <span>process</span> to ensure you get the best results, every step of the way.</p></div>
          <ol className="grid grid-cols-4 gap-y-10 gap-x-10 list-none pt-0 pr-0 pb-0 pl-0 mt-0 mr-0 mb-0 ml-0 [&_li]:relative [&_li]:text-center [&_h3]:max-w-57.5 [&_h3]:mt-0 [&_h3]:mr-auto [&_h3]:mb-2.5 [&_h3]:ml-auto [&_h3]:text-[length:21px] [&_h3]:leading-[1.1] [&_p]:max-w-52.5 [&_p]:mt-0 [&_p]:mr-auto [&_p]:mb-0 [&_p]:ml-auto [&_p]:text-[length:16px] [&_p]:leading-[1.4] max-[800px]:grid-cols-2 max-[800px]:gap-y-7.5 max-[800px]:gap-x-7.5 max-[800px]:[&_h3]:text-[length:21px] max-[540px]:gap-y-7 max-[540px]:gap-x-4.5 max-[540px]:[&_h3]:text-[length:18px] max-[540px]:[&_p]:text-[length:14px]">{steps.map(({ icon: Icon, title, description }, index) => <li key={title}><span className="grid place-items-center w-19.5 h-19.5 mt-0 mr-auto mb-4 ml-auto [border:1px_solid_#229fff] rounded-[50%] [&_svg]:w-9.25 [&_svg]:h-9.25 max-[540px]:w-16.25 max-[540px]:h-16.25 app-services-page-stepIcon [background-image:linear-gradient(120deg,_#0081ed,_#005cba)]"><Icon aria-hidden="true" /></span><h3>{index + 1}. {title}</h3><p>{description}</p>{index < steps.length - 1 && <ArrowRight className="absolute w-[44%] h-5 text-[#36a9eb] top-7.25 right-[-30%] [stroke-width:1] max-[800px]:hidden" aria-hidden="true" />}</li>)}</ol>
        </div>
      </section>

      <section className="app-services-page-commitment [background-image:linear-gradient(120deg,_#f4f9fd,_#f7fbfd)]" aria-labelledby="commitment-title">
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container  grid grid-cols-[1fr_.95fr_1.1fr] gap-y-8.75 gap-x-8.75 [align-items:start] max-[1100px]:gap-y-6 max-[1100px]:gap-x-6 max-[1100px]:grid-cols-[1fr_1fr] max-[540px]:grid-cols-1">
          <div className="[&_ul]:flex [&_ul]:flex-col [&_ul]:gap-y-2.25 [&_ul]:gap-x-2.25 [&_ul]:mt-4.5 [&_ul]:mr-0 [&_ul]:mb-5.5 [&_ul]:ml-0 [&_ul]:pt-0 [&_ul]:pr-0 [&_ul]:pb-0 [&_ul]:pl-0 [&_ul]:list-none [&_li]:flex [&_li]:items-start [&_li]:gap-y-2.5 [&_li]:gap-x-2.5 [&_li]:text-[length:14px] [&_li]:leading-[1.4] [&_li]:text-[#495970] [&_li_span]:grid [&_li_span]:place-items-center [&_li_span]:shrink-0 [&_li_span]:w-4.5 [&_li_span]:h-4.5 [&_li_span]:mt-0.25 [&_li_span]:rounded-[50%] [&_li_span]:bg-[#006ad0] [&_li_span]:text-[#fff] app-services-page-commitmentCopy [&_>_p:not(.app-services-page-eyebrow)]:[color:#4d5f74] [&_>_p:not(.app-services-page-eyebrow)]:[font-size:16px] [&_>_p:not(.app-services-page-eyebrow)]:[line-height:1.5]"><p className="mt-0 mr-0 mb-3 ml-0 text-[length:12px] font-semibold leading-[1.5] tracking-[.2em] uppercase app-services-page-eyebrow">Why Work With Us</p><h2 id="commitment-title">Your Goals.<br />Our Commitment.</h2><span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /><p>We combine professional expertise with a personalized approach to deliver solutions that make a real difference in your financial life.</p><ul>{["Experienced and certified professionals", "Client-centered and transparent process", "Customized solutions for every stage of life", "Trusted by individuals, SMEs and non-profits", "Support across Canada and internationally"].map((item) => <li key={item}><span><Check size={12} aria-hidden="true" /></span>{item}</li>)}</ul><Link href="/#contact" className="inline-flex items-center justify-center gap-y-2.5 gap-x-2.5 min-h-11.25 pt-3 pr-6 pb-3 pl-6 rounded-[5px] text-[#fff] text-[length:14px] bg-[#006bcf] [transition:background_160ms_ease] hover:bg-[#004f9e] motion-reduce:[transition:none]">Work With Us <ArrowRight size={17} aria-hidden="true" /></Link></div>
          <figure className="relative overflow-hidden self-stretch min-h-105 mt-0 mr-0 mb-0 ml-0 rounded-[7px] bg-[#07304e] [&_img]:object-cover [&_img]:object-[38%] [&_figcaption]:absolute [&_figcaption]:top-[12%] [&_figcaption]:left-[7%] [&_figcaption]:right-[7%] [&_figcaption]:pt-3.75 [&_figcaption]:pr-3.75 [&_figcaption]:pb-3.75 [&_figcaption]:pl-3.75 [&_figcaption]:rounded-[5px] [&_figcaption]:bg-[#001c3380] [&_figcaption]:text-[white] [&_figcaption]:font-serif [&_figcaption]:text-[length:clamp(24px,_2.1vw,_33px)] [&_figcaption]:font-bold [&_figcaption]:leading-[1.2] [&_figcaption]:tracking-[.03em] [&_figcaption]:uppercase max-[540px]:min-h-90 app-services-page-commitmentPhoto [&_.app-services-page-redLine]:[width:110px] [&_.app-services-page-redLine]:[transform:rotate(-12deg)]"><Image src="/images/about/leadership.png" alt="A professional reviewing documents and writing notes beside a laptop" fill sizes="(max-width: 900px) 100vw, 30vw" /><figcaption>People<br />Process<br />Possibilities<span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /></figcaption></figure>
          <div id="faqs" className={`scroll-mt-28.75 [&_h2]:text-[length:clamp(25px,_2vw,_31px)] [&_details]:bg-[#fff] [&_details]:mb-2 [&_details]:rounded-[5px] [&_details]:shadow-[0_3px_10px_#193d5d04] [&_summary]:flex [&_summary]:items-center [&_summary]:justify-between [&_summary]:gap-y-3.5 [&_summary]:gap-x-3.5 [&_summary]:pt-3.75 [&_summary]:pr-4.25 [&_summary]:pb-3.75 [&_summary]:pl-4.25 [&_summary]:text-[length:15px] [&_summary]:leading-[1.4] [&_summary]:cursor-pointer [&_summary]:list-none [&_details_>_p]:mt-0 [&_details_>_p]:mr-0 [&_details_>_p]:mb-0 [&_details_>_p]:ml-0 [&_details_>_p]:pt-0 [&_details_>_p]:pr-4.25 [&_details_>_p]:pb-4.5 [&_details_>_p]:pl-4.25 [&_details_>_p]:text-[length:14px] [&_details_>_p]:text-[#596678] [&_details_>_p]:leading-[1.5] max-[1100px]:[grid-column:1_/_-1] max-[540px]:[grid-column:auto] app-services-page-faqs [&_summary::-webkit-details-marker]:[display:none] [&_summary_span::before]:[content:"+"] [&_summary_span::before]:[font-size:20px] [&_details[open]_summary_span::before]:[content:"−"]`}><h2>Frequently Asked Questions</h2><span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" />{faqs.map(({ question, answer }, index) => <details key={question} name="services-faq" open={index === 0}><summary>{question}<span aria-hidden="true" /></summary><p>{answer}</p></details>)}<Link href="/#contact" className="inline-flex items-center gap-y-1.5 gap-x-1.5 mt-4.25 text-[#0069dc] text-[length:15px]">Have another question? <ArrowRight size={16} aria-hidden="true" /></Link></div>
        </div>
      </section>

      <section className={`[&_h2_span]:text-[#279fe9] relative isolate text-[#fff] bg-[#001e38] [&_>_img]:z-[-2] [&_>_img]:object-cover [&_>_img]:object-center [&_>_img]:opacity-[.55] max-[540px]:[&_h2]:text-[length:31px] app-services-page-cta [&::after]:[position:absolute] [&::after]:[z-index:-1] [&::after]:[inset:0] [&::after]:[background-image:linear-gradient(90deg,_#001b34ed,_#001b3430,_#001b34de)] [&::after]:[content:""] [&_.app-services-page-container]:[display:flex] [&_.app-services-page-container]:[justify-content:space-between] [&_.app-services-page-container]:[align-items:center] [&_.app-services-page-container]:[gap:35px] [@media(max-width:_800px)]:[&_.app-services-page-container]:[flex-direction:column] [@media(max-width:_800px)]:[&_.app-services-page-container]:[align-items:flex-start] [@media(max-width:_800px)]:[&_.app-services-page-container]:[gap:24px]`} aria-labelledby="services-cta-title"><Image src="/images/about/cta.png" alt="" fill sizes="100vw" /><div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container"><div><p className="mt-0 mr-0 mb-3 ml-0 text-[length:12px] font-semibold leading-[1.5] tracking-[.2em] uppercase app-services-page-eyebrow">Ready to Take the Next Step?</p><h2 id="services-cta-title">Let’s Build a Stronger<br />Financial Future <span>Together</span></h2></div><div className="[&_p]:text-[length:15px] [&_p]:leading-[1.5] [&_p]:mt-0 [&_p]:mr-0 [&_p]:mb-4.5 [&_p]:ml-0"><p>Have questions or need expert guidance?<br />We’re here to help.</p><Link href="/#contact" className="inline-flex items-center justify-center gap-y-2.5 gap-x-2.5 min-h-11.25 pt-3 pr-6 pb-3 pl-6 rounded-[5px] text-[#fff] text-[length:14px] bg-[#f10b29] [transition:background_160ms_ease] hover:bg-[#c90822] motion-reduce:[transition:none]">Get in Touch <ArrowRight size={17} aria-hidden="true" /></Link></div></div></section>
    </main>
  );
}
