import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ChartNoAxesCombined, Check, Files, GraduationCap, ShieldCheck, UserRound, UsersRound, Wallet, Banknote } from "lucide-react";

import { serviceOfferings, serviceBenefits } from "@/lib/services";
import FAQSection from "@/components/services/faq-section";
import ProcessSection from "@/components/services/process-section";

const serviceIcons = [Files, UserRound, Wallet, Banknote, ChartNoAxesCombined, GraduationCap, ShieldCheck];
const services = serviceOfferings.map((service, index) => ({ ...service, icon: serviceIcons[index] }));
const faqs = [
  { question: "Can you work within my budget?", answer: "Yes. Our approach is flexible, scalable, and designed around your unique needs. We never leave a client behind because of affordability or stage of business." },
  { question: "Do you work with small businesses?", answer: "Yes. We work closely with small and medium-sized businesses, from basic bookkeeping to a complete finance function. We design solutions that fit your business and budget." },
  { question: "How do I get started?", answer: "Contact us with a brief description of your needs and the service you are interested in. We will discuss your goals, answer your questions, and agree on the next steps." },
  { question: "Are your services confidential?", answer: "We treat your information with care. Before sharing sensitive financial documents, contact our team to confirm the appropriate secure method and discuss confidentiality requirements." },
  { question: "Do you offer virtual consultations?", answer: "Contact our team to arrange a consultation and discuss a remote meeting option that works for your location and schedule." },
];

export default function ServicesPage() {
  return (
    <main className="font-body text-ink [&_h1]:font-heading [&_h1]:font-bold [&_h2]:font-heading [&_h2]:font-bold [&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h2]:text-section [&_h3]:font-heading [&_h3]:font-semibold [&_a:focus-visible]:[outline:3px_solid_#2c99ef] [&_a:focus-visible]:outline-offset-[5px] [&_summary:focus-visible]:[outline:3px_solid_#2c99ef] [&_summary:focus-visible]:outline-offset-[5px]">
      <section className="typography-inverse relative isolate overflow-hidden bg-[#021e39] text-white [&_h1]:mt-0 [&_h1]:mr-0 [&_h1]:mb-0 [&_h1]:ml-0 [&_h1]:text-title [&_h1_span]:text-heading-accent" aria-labelledby="services-title">
        <Image src="/images/services/hero.png" alt="Fountain pen and financial reports on a modern office desk" fill sizes="100vw" preload className="z-[-2] object-cover object-center" />
        <div className="absolute z-[-1] top-0 right-[37%] bottom-0 left-0 [border-right:12px_solid_#82d0ff45] max-[800px]:top-0 max-[800px]:right-0 max-[800px]:bottom-0 max-[800px]:left-0 max-[800px]:[border:0] app-services-page-heroPanel [background-image:linear-gradient(110deg,_#001b36fc,_#002040f5)] [clip-path:polygon(0_0,_82%_0,_100%_100%,_0_100%)] [@media(max-width:_800px)]:[clip-path:none] [@media(max-width:_800px)]:[background-image:linear-gradient(90deg,_#001b34f5,_#001b34e0_60%,_#001b3470)]" aria-hidden="true" />
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-7 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-7.5 max-[540px]:pr-5 max-[540px]:pb-7.5 max-[540px]:pl-5">
          <nav aria-label="Breadcrumb" className="flex gap-y-3 gap-x-3 text-heading-accent text-body mb-6.25"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Our Services</span></nav>
          <div className="w-[55%] max-w-172.5 max-[800px]:w-[90%] max-[540px]:w-full">
            <h1 id="services-title">Our <span>Services</span></h1>
            <p className="text-body mt-2.5 mr-0 mb-0 ml-0">Practical Solutions. Professional Expertise.<br />Affordable Support.</p>
            <span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" />
            <p className="text-body mt-0 mr-0 mb-0 ml-0 max-w-162.5">At RD Prestige Services Corp. (RDPSC), we believe every business and individual deserves access to high-quality financial and professional services, regardless of size, stage of growth, or budget.</p>
            <ul className={`grid grid-cols-3 list-none mt-6.25 mr-0 mb-0 ml-0 pt-0 pr-0 pb-0 pl-0 max-w-145 [&_li]:relative [&_li]:text-center [&_li]:text-body [&_svg]:block [&_svg]:mt-0 [&_svg]:mr-auto [&_svg]:mb-2 [&_svg]:ml-auto [&_svg]:w-9.25 [&_svg]:h-9.25 [&_svg]:text-heading-accent max-[540px]:[&_svg]:w-7.75 max-[540px]:[&_svg]:h-7.75 app-services-page-trust [&_li_+_li::before]:[position:absolute] [&_li_+_li::before]:[left:0] [&_li_+_li::before]:[bottom:8px] [&_li_+_li::before]:[height:45%] [&_li_+_li::before]:[width:1px] [&_li_+_li::before]:[background:#2e9cd9] [&_li_+_li::before]:[content:""]`}><li><ShieldCheck aria-hidden="true" />Trusted<br />Expertise</li><li><UsersRound aria-hidden="true" />Client<br />Focused</li><li><ChartNoAxesCombined aria-hidden="true" />Real<br />Results</li></ul>
          </div>
        </div>
        <p className={`absolute top-11.25 right-[5%] text-ink font-heading text-body italic [transform:rotate(-12deg)] max-[800px]:hidden app-services-page-heroSignature [&_.app-services-page-redLine]:[width:120px]`}>Your<br />Financial Partner<br />for a Brighter<br />Tomorrow<span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" /></p>
      </section>

      <section className="app-services-page-areas [background-image:linear-gradient(120deg,_#f4f9fd,_#f7fbfd)]" aria-labelledby="service-areas-title">
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container">
          <div className="flex items-center justify-between gap-y-10 gap-x-10 [&_>_div]:flex-[1.4] [&_>_p]:flex-1 [&_>_p]:max-w-125 [&_>_p]:text-body [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-3.75 [&_>_p]:ml-0 max-[800px]:flex-col max-[800px]:items-start max-[800px]:gap-y-0 max-[800px]:gap-x-0 max-[800px]:[&_>_p]:max-w-full max-[800px]:[&_>_p]:mb-6 app-services-page-sectionHeader"><div><p className="mt-0 mr-0 mb-3 ml-0 text-caption font-semibold tracking-[.14em] uppercase app-services-page-eyebrow">Our Service Areas</p><h2 id="service-areas-title">Services Designed Around Your Needs</h2><span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /></div><p>Whether you are launching a new venture, scaling a growing business, managing personal finances, or implementing a major organizational change, our team provides tailored solutions that meet you where you are today and grow with you tomorrow.</p></div>
          <div className="grid grid-cols-4 gap-y-5 gap-x-5 [align-items:start] max-[1100px]:gap-y-4 max-[1100px]:gap-x-4 max-[800px]:grid-cols-2 max-[540px]:grid-cols-1">
            {services.map(({ id, icon: Icon, title, summary }) => (
              <article id={id} className="typography-surface flex flex-col items-center min-h-85 pt-6 pr-6 pb-5.5 pl-6 rounded-[9px] bg-[#fff] shadow-[0_5px_16px_#153c6a09] text-center scroll-mt-28.75 [&_h3]:max-w-57.5 [&_h3]:min-h-13 [&_h3]:mt-4.5 [&_h3]:mr-0 [&_h3]:mb-3.25 [&_h3]:ml-0 [&_h3]:text-card-heading [&_>_p]:text-copy [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-5 [&_>_p]:ml-0 [&_>_p]:text-body max-[1100px]:pl-4 max-[1100px]:pr-4 max-[1100px]:min-h-87.5 max-[800px]:min-h-82.5 max-[540px]:min-h-0 max-[540px]:pt-6.25 max-[540px]:pr-6.25 max-[540px]:pb-6.25 max-[540px]:pl-6.25 max-[540px]:[&_h3]:min-h-0 max-[540px]:[&_h3]:max-w-62.5" key={id}>
                <span className="grid place-items-center w-20.75 h-20.75 shrink-0 rounded-[50%] bg-[#eef5ff] text-heading-accent [&_svg]:w-11.5 [&_svg]:h-11.5 [&_svg]:[stroke-width:1.65]"><Icon aria-hidden="true" /></span><h3><Link href={`/services/${id}`} className="hover:text-heading-accent">{title}</Link></h3><p>{summary}</p>
                <Link href={`/services/${id}`} aria-label={`Learn more about ${title}`} className="mt-auto inline-flex min-h-11 items-center justify-center gap-2 font-semibold text-heading-accent hover:underline">Learn More <ArrowRight size={16} aria-hidden="true" /></Link>
              </article>
            ))}
            <aside className="relative isolate self-stretch overflow-hidden rounded-[9px] min-h-85 bg-[#dfedfa] [&_>_img]:z-[-1] [&_>_img]:object-cover [&_>_img]:object-[80%] [&_>_img]:opacity-[.45] [&_>_div]:pt-10 [&_>_div]:pr-6.25 [&_>_div]:pb-6 [&_>_div]:pl-6.25 [&_h3]:[border-left:4px_solid_#ff193b] [&_h3]:pl-5 [&_h3]:mt-5 [&_h3]:mr-0 [&_h3]:mb-5 [&_h3]:ml-0 [&_h3]:text-subheading max-[1100px]:[&_>_div]:pl-4.5 max-[1100px]:[&_>_div]:pr-4.5 max-[1100px]:[&_h3]:pl-3 max-[540px]:min-h-75 max-[540px]:[&_>_div]:pt-7.5 max-[540px]:[&_>_div]:pr-7.5 max-[540px]:[&_>_div]:pb-7.5 max-[540px]:[&_>_div]:pl-7.5 app-services-page-partnerCard [&_.app-services-page-eyebrow]:text-caption">
              <Image src="/images/financial-future-background.png" alt="" fill sizes="(max-width: 600px) 100vw, 25vw" />
              <div><p className="mt-0 mr-0 mb-3 ml-0 text-caption font-semibold tracking-[.14em] uppercase app-services-page-eyebrow">More Than Services</p><h3>A Partner<br />in Your<br />Financial<br />Journey</h3><Link href="/#contact" className="typography-inverse inline-flex items-center justify-center gap-y-2.5 gap-x-2.5 min-h-11.25 pt-3 pr-6 pb-3 pl-6 rounded-[5px] text-white text-caption bg-[#006bcf] [transition:background_160ms_ease] hover:bg-[#004f9e] motion-reduce:[transition:none]">Get in Touch <ArrowRight size={17} aria-hidden="true" /></Link></div>
            </aside>
          </div>
        </div>
      </section>

      <ProcessSection />

      <section className="app-services-page-commitment [background-image:linear-gradient(120deg,_#f4f9fd,_#f7fbfd)]" aria-labelledby="commitment-title">
        <div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container grid grid-cols-2 gap-10 items-start max-[800px]:grid-cols-1 max-[540px]:gap-7">
          <div className="[&_ul]:flex [&_ul]:flex-col [&_ul]:gap-y-2.25 [&_ul]:gap-x-2.25 [&_ul]:mt-4.5 [&_ul]:mr-0 [&_ul]:mb-5.5 [&_ul]:ml-0 [&_ul]:pt-0 [&_ul]:pr-0 [&_ul]:pb-0 [&_ul]:pl-0 [&_ul]:list-none [&_li]:flex [&_li]:items-start [&_li]:gap-y-2.5 [&_li]:gap-x-2.5 [&_li]:text-body [&_li]:text-copy [&_li_span]:grid [&_li_span]:place-items-center [&_li_span]:shrink-0 [&_li_span]:w-4.5 [&_li_span]:h-4.5 [&_li_span]:mt-0.25 [&_li_span]:rounded-[50%] [&_li_span]:bg-[#006ad0] [&_li_span]:text-white app-services-page-commitmentCopy [&_>_p:not(.app-services-page-eyebrow)]:[color:var(--color-copy)] [&_>_p:not(.app-services-page-eyebrow)]:text-body [&_>_p:not(.app-services-page-eyebrow)]:[line-height:1.7]"><p className="mt-0 mr-0 mb-3 ml-0 text-caption font-semibold tracking-[.14em] uppercase app-services-page-eyebrow">Why Work With Us</p><h2 id="commitment-title">Your Goals.<br />Our Commitment.</h2><span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /><p>We never leave a client behind because of affordability or stage of business. Our approach is flexible, scalable, and designed around your unique needs.</p><ul>{serviceBenefits.map((item) => <li key={item}><span><Check size={12} aria-hidden="true" /></span>{item}</li>)}</ul><Link href="/#contact" className="typography-inverse inline-flex items-center justify-center gap-y-2.5 gap-x-2.5 min-h-11.25 pt-3 pr-6 pb-3 pl-6 rounded-[5px] text-white text-caption bg-[#006bcf] [transition:background_160ms_ease] hover:bg-[#004f9e] motion-reduce:[transition:none]">Work With Us <ArrowRight size={17} aria-hidden="true" /></Link></div>
          <figure className="relative overflow-hidden self-stretch min-h-105 mt-0 mr-0 mb-0 ml-0 rounded-[7px] bg-[#07304e] [&_img]:object-cover [&_img]:object-[38%] [&_figcaption]:absolute [&_figcaption]:top-[12%] [&_figcaption]:left-[7%] [&_figcaption]:right-[7%] [&_figcaption]:pt-3.75 [&_figcaption]:pr-3.75 [&_figcaption]:pb-3.75 [&_figcaption]:pl-3.75 [&_figcaption]:rounded-[5px] [&_figcaption]:bg-[#001c3380] [&_figcaption]:text-white [&_figcaption]:font-heading [&_figcaption]:text-subheading [&_figcaption]:font-bold [&_figcaption]:uppercase max-[540px]:min-h-90 app-services-page-commitmentPhoto [&_.app-services-page-redLine]:[width:110px] [&_.app-services-page-redLine]:[transform:rotate(-12deg)]"><Image src="/images/about/leadership.png" alt="A professional reviewing documents and writing notes beside a laptop" fill sizes="(max-width: 800px) 100vw, 50vw" /><figcaption>People<br />Process<br />Possibilities<span className="block w-12 h-0.75 mt-5 mr-0 mb-5 ml-0 bg-[#ff1534] app-services-page-redLine" aria-hidden="true" /></figcaption></figure>

        </div>
      </section>

      <FAQSection faqs={faqs} />

      <section className={`typography-inverse [&_h2_span]:text-heading-accent relative isolate text-white bg-[#001e38] [&_>_img]:z-[-2] [&_>_img]:object-cover [&_>_img]:object-center [&_>_img]:opacity-[.55] [&_h2]:text-section app-services-page-cta [&::after]:[position:absolute] [&::after]:[z-index:-1] [&::after]:[inset:0] [&::after]:[background-image:linear-gradient(90deg,_#001b34ed,_#001b3430,_#001b34de)] [&::after]:[content:""] [&_.app-services-page-container]:[display:flex] [&_.app-services-page-container]:[justify-content:space-between] [&_.app-services-page-container]:[align-items:center] [&_.app-services-page-container]:[gap:35px] [@media(max-width:_800px)]:[&_.app-services-page-container]:[flex-direction:column] [@media(max-width:_800px)]:[&_.app-services-page-container]:[align-items:flex-start] [@media(max-width:_800px)]:[&_.app-services-page-container]:[gap:24px]`} aria-labelledby="services-cta-title"><Image src="/images/about/cta.png" alt="" fill sizes="100vw" /><div className="max-w-360 mt-auto mr-auto mb-auto ml-auto pt-10.5 pr-[clamp(24px,_4.5vw,_65px)] pb-10.5 pl-[clamp(24px,_4.5vw,_65px)] max-[540px]:pt-8 max-[540px]:pr-5 max-[540px]:pb-8 max-[540px]:pl-5 app-services-page-container"><div><p className="mt-0 mr-0 mb-3 ml-0 text-caption font-semibold tracking-[.14em] uppercase app-services-page-eyebrow">Ready to Take the Next Step?</p><h2 id="services-cta-title">Let’s Build a Stronger<br />Financial Future <span>Together</span></h2></div><div className="[&_p]:text-body [&_p]:mt-0 [&_p]:mr-0 [&_p]:mb-4.5 [&_p]:ml-0"><p>Have questions or need expert guidance?<br />We’re here to help.</p><Link href="/#contact" className="inline-flex items-center justify-center gap-y-2.5 gap-x-2.5 min-h-11.25 pt-3 pr-6 pb-3 pl-6 rounded-[5px] text-white text-caption bg-[#f10b29] [transition:background_160ms_ease] hover:bg-[#c90822] motion-reduce:[transition:none]">Get in Touch <ArrowRight size={17} aria-hidden="true" /></Link></div></div></section>
    </main>
  );
}
