import { company } from "@/lib/company";
import Image from "next/image";
import Link from "next/link";
import { CalendarDays, Check, Mail, PhoneCall } from "lucide-react";
import ConsultationForm from "@/components/consultation/consultation-form";

export default function ConsultationPage() {
  return (
    <main className="bg-[var(--indigo-50)] text-ink font-body [&_h1]:font-heading [&_h1]:font-bold [&_h2]:font-heading [&_h2]:font-bold [&_a:focus-visible]:[outline:3px_solid_var(--cyan-700)] [&_a:focus-visible]:outline-offset-[4px] [&_button:focus-visible]:[outline:3px_solid_var(--cyan-700)] [&_button:focus-visible]:outline-offset-[4px]">
      <section className={`typography-inverse relative overflow-hidden text-white [&_h1]:mt-0 [&_h1]:mr-0 [&_h1]:mb-0 [&_h1]:ml-0 [&_h1]:text-title [&_h1_em]:text-heading-accent app-consultation-page-hero [background-image:radial-gradient(ellipse_at_90%_20%,_var(--indigo-800),_transparent_55%),_linear-gradient(120deg,_var(--indigo-900),_var(--indigo-900))] [&::after]:[position:absolute] [&::after]:[right:-60px] [&::after]:[top:-240px] [&::after]:[width:550px] [&::after]:[height:550px] [&::after]:[border:70px_solid_#2098C80a] [&::after]:[transform:rotate(40deg)] [&::after]:[content:""] [&::after]:[pointer-events:none] [&_.app-consultation-page-eyebrow]:[color:var(--cyan-300)]`} aria-labelledby="consultation-title">
        <div className="relative z-[1] max-w-335 mt-auto mr-auto mb-auto ml-auto pt-7.5 pr-10 pb-14.5 pl-10 max-[1050px]:pl-7 max-[1050px]:pr-7 max-[540px]:pt-6.25 max-[540px]:pr-5 max-[540px]:pb-8.75 max-[540px]:pl-5">
          <nav className="flex flex-wrap gap-y-3 gap-x-3 text-inverse-accent text-body mb-8" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Request a Consultation</span></nav>
          <p className="flex items-center gap-y-2.25 gap-x-2.25 mt-0 mr-0 mb-3.5 ml-0 text-heading-accent text-caption font-bold tracking-[.14em] uppercase app-consultation-page-eyebrow"><CalendarDays size={18} aria-hidden="true" /> Let’s Plan Your Next Step</p>
          <h1 id="consultation-title">Your Goals. Our Expertise.<br /><em>A Conversation That Matters.</em></h1>
          <p className="mt-5 mr-0 mb-5.75 ml-0 max-w-170 text-inverse-copy text-body">Whether you’re planning for yourself or growing an organization, start with a conversation about what matters to you.</p>
          <ul className="flex flex-wrap gap-y-3.5 gap-x-6.25 list-none pt-0 pr-0 pb-0 pl-0 mt-0 mr-0 mb-0 ml-0 [&_li]:flex [&_li]:items-center [&_li]:gap-y-2 [&_li]:gap-x-2 [&_li]:text-inverse-copy [&_li]:text-small [&_svg]:text-heading-accent max-[540px]:gap-y-3 max-[540px]:gap-x-3">{["Personalized guidance", "Practical next steps", "Canada & internationally"].map((text) => <li key={text}><Check size={16} aria-hidden="true" />{text}</li>)}</ul>
        </div>
      </section>

      <div className="grid grid-cols-[.8fr_1.3fr] gap-y-9.5 gap-x-9.5 max-w-335 pt-11 pr-10 pb-16.25 pl-10 mt-auto mr-auto mb-auto ml-auto [align-items:start] max-[1050px]:gap-y-6.25 max-[1050px]:gap-x-6.25 max-[1050px]:pl-7 max-[1050px]:pr-7 max-[850px]:grid-cols-1 max-[850px]:max-w-185 max-[540px]:pt-6.25 max-[540px]:pr-5 max-[540px]:pb-10 max-[540px]:pl-5">
        <aside className="min-w-0" aria-labelledby="expect-heading">
          <figure className="relative h-61.25 mt-0 mr-0 mb-7.5 ml-0 rounded-[13px] overflow-hidden bg-[var(--indigo-900)] [&_img]:object-cover [&_img]:object-[center_52%] [&_figcaption]:absolute [&_figcaption]:bottom-0 [&_figcaption]:left-0 [&_figcaption]:right-0 [&_figcaption]:pt-8.75 [&_figcaption]:pr-5.5 [&_figcaption]:pb-5 [&_figcaption]:pl-5.5 [&_figcaption]:text-white [&_figcaption]:font-heading [&_figcaption]:text-body [&_figcaption]:italic max-[850px]:h-80 max-[540px]:h-65 app-consultation-page-photo [&_figcaption]:[background-image:linear-gradient(transparent,_#1B2260d9)]"><Image src="/images/about-consultation.png" alt="Illustration of financial professionals discussing a client's goals" fill sizes="(max-width: 850px) 100vw, 35vw" /><figcaption>Clarity starts with a conversation.</figcaption></figure>
          <div className="[&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h2]:text-section [&_ol]:list-none [&_ol]:mt-6.25 [&_ol]:mr-0 [&_ol]:mb-6.25 [&_ol]:ml-0 [&_ol]:pt-0 [&_ol]:pr-0 [&_ol]:pb-0 [&_ol]:pl-0 [&_ol]:flex [&_ol]:flex-col [&_ol]:gap-y-6 [&_ol]:gap-x-6 [&_li]:flex [&_li]:gap-y-3.75 [&_li]:gap-x-3.75 [&_li_>_span]:grid [&_li_>_span]:place-items-center [&_li_>_span]:shrink-0 [&_li_>_span]:w-9.5 [&_li_>_span]:h-9.5 [&_li_>_span]:rounded-[50%] [&_li_>_span]:[border:1px_solid_var(--line)] [&_li_>_span]:bg-white [&_li_>_span]:text-heading-accent [&_li_>_span]:text-small [&_li_>_span]:font-bold [&_h3]:mt-0 [&_h3]:mr-0 [&_h3]:mb-1.5 [&_h3]:ml-0 [&_h3]:text-card-heading [&_h3]:font-semibold [&_li_p]:mt-0 [&_li_p]:mr-0 [&_li_p]:mb-0 [&_li_p]:ml-0 [&_li_p]:text-copy [&_li_p]:text-body"><p className="flex items-center gap-y-2.25 gap-x-2.25 mt-0 mr-0 mb-3.5 ml-0 text-heading-accent text-caption font-bold tracking-[.14em] uppercase app-consultation-page-eyebrow">A Simple Start</p><h2 id="expect-heading">What happens next?</h2><ol>{[{title:"Tell us what you need",text:"Share your goals and choose the service you’d like to discuss."},{title:"We connect with you",text:"Our team follows up using your preferred contact method to discuss availability."},{title:"Plan the way forward",text:"Together, we clarify your priorities and the next steps that fit your needs."}].map(({title,text},index)=><li key={title}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div>
          <div className="pt-5.5 pr-5.5 pb-5.5 pl-5.5 [border:1px_solid_var(--line)] rounded-[10px] bg-white [&_h3]:text-card-heading [&_h3]:font-semibold [&_h3]:mt-0 [&_h3]:mr-0 [&_h3]:mb-3.75 [&_h3]:ml-0 [&_a]:flex [&_a]:items-center [&_a]:gap-y-2.5 [&_a]:gap-x-2.5 [&_a]:text-body [&_a]:mt-3 [&_svg]:text-heading-accent [&_p]:text-small [&_p]:text-copy [&_p]:mt-3.75 [&_p]:mr-0 [&_p]:mb-0 [&_p]:ml-0"><h3>Prefer to speak with us?</h3>{company.phones.map(({ href, label }) => <a key={href} href={href} className="min-h-11 hover:underline"><PhoneCall size={18} aria-hidden="true" />{label}</a>)}<a href={company.emailHref}><Mail size={18} aria-hidden="true" />{company.email}</a><p>Mon – Fri · 9:00 AM – 6:00 PM EST</p></div>
        </aside>
        <section className="typography-surface min-w-0 pt-8.5 pr-8.5 pb-8.5 pl-8.5 [border:1px_solid_var(--line)] rounded-[14px] bg-[var(--white)] shadow-[0_12px_35px_#1B226008] [&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h2]:text-section max-[1050px]:pt-6.5 max-[1050px]:pr-6.5 max-[1050px]:pb-6.5 max-[1050px]:pl-6.5 max-[850px]:[grid-row:1] max-[540px]:pt-6.25 max-[540px]:pr-4.5 max-[540px]:pb-6.25 max-[540px]:pl-4.5" aria-labelledby="consultation-form-heading"><p className="flex items-center gap-y-2.25 gap-x-2.25 mt-0 mr-0 mb-3.5 ml-0 text-heading-accent text-caption font-bold tracking-[.14em] uppercase app-consultation-page-eyebrow">Let’s Get to Know You</p><h2 id="consultation-form-heading">Request a Consultation</h2><p className="mt-3.5 mr-0 mb-7 ml-0 text-caption text-copy [&_span]:text-[var(--red-600)]">Tell us a little about yourself and how we can help. Fields marked <span>*</span> are required.</p><ConsultationForm /></section>
      </div>
    </main>
  );
}
