import Image from "next/image";
import Link from "next/link";
import { CalendarDays, Check, Mail, PhoneCall } from "lucide-react";
import ConsultationForm from "@/components/consultation/consultation-form";

export default function ConsultationPage() {
  return (
    <main className="bg-[#f3f7fc] text-[#112744] font-body [&_h1]:font-serif [&_h1]:font-bold [&_h1]:tracking-[-.025em] [&_h2]:font-serif [&_h2]:font-bold [&_h2]:tracking-[-.025em] [&_a:focus-visible]:[outline:3px_solid_#3297ec] [&_a:focus-visible]:outline-offset-[4px] [&_button:focus-visible]:[outline:3px_solid_#3297ec] [&_button:focus-visible]:outline-offset-[4px]">
      <section className={`relative overflow-hidden text-[#fff] [&_h1]:mt-0 [&_h1]:mr-0 [&_h1]:mb-0 [&_h1]:ml-0 [&_h1]:text-[length:clamp(36px,_3.8vw,_57px)] [&_h1]:leading-[1.13] [&_h1_em]:text-[#41b7fa] max-[850px]:[&_h1]:text-[length:42px] max-[540px]:[&_h1]:text-[length:35px] app-consultation-page-hero [background-image:radial-gradient(ellipse_at_90%_20%,_#124d7e,_transparent_55%),_linear-gradient(120deg,_#001b32,_#052c4c)] [&::after]:[position:absolute] [&::after]:[right:-60px] [&::after]:[top:-240px] [&::after]:[width:550px] [&::after]:[height:550px] [&::after]:[border:70px_solid_#59b3e60a] [&::after]:[transform:rotate(40deg)] [&::after]:[content:""] [&::after]:[pointer-events:none] [&_.app-consultation-page-eyebrow]:[color:#68c6fb]`} aria-labelledby="consultation-title">
        <div className="relative z-[1] max-w-335 mt-auto mr-auto mb-auto ml-auto pt-7.5 pr-10 pb-14.5 pl-10 max-[1050px]:pl-7 max-[1050px]:pr-7 max-[540px]:pt-6.25 max-[540px]:pr-5 max-[540px]:pb-8.75 max-[540px]:pl-5">
          <nav className="flex flex-wrap gap-y-3 gap-x-3 text-[#8ccbec] text-[length:14px] mb-8" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Request a Consultation</span></nav>
          <p className="flex items-center gap-y-2.25 gap-x-2.25 mt-0 mr-0 mb-3.5 ml-0 text-[#3389c9] text-[length:11px] font-bold tracking-[.17em] leading-[1.5] uppercase app-consultation-page-eyebrow"><CalendarDays size={18} aria-hidden="true" /> Let’s Plan Your Next Step</p>
          <h1 id="consultation-title">Your Goals. Our Expertise.<br /><em>A Conversation That Matters.</em></h1>
          <p className="mt-5 mr-0 mb-5.75 ml-0 max-w-170 text-[#d5e3f1] text-[length:19px] leading-[1.6] max-[540px]:text-[length:17px]">Whether you’re planning for yourself or growing an organization, start with a conversation about what matters to you.</p>
          <ul className="flex flex-wrap gap-y-3.5 gap-x-6.25 list-none pt-0 pr-0 pb-0 pl-0 mt-0 mr-0 mb-0 ml-0 [&_li]:flex [&_li]:items-center [&_li]:gap-y-2 [&_li]:gap-x-2 [&_li]:text-[#e2eef8] [&_li]:text-[length:13px] [&_svg]:text-[#5ec7ff] max-[540px]:gap-y-3 max-[540px]:gap-x-3 max-[540px]:[&_li]:text-[length:12px]">{["Personalized guidance", "Practical next steps", "Canada & internationally"].map((text) => <li key={text}><Check size={16} aria-hidden="true" />{text}</li>)}</ul>
        </div>
      </section>

      <div className="grid grid-cols-[.8fr_1.3fr] gap-y-9.5 gap-x-9.5 max-w-335 pt-11 pr-10 pb-16.25 pl-10 mt-auto mr-auto mb-auto ml-auto [align-items:start] max-[1050px]:gap-y-6.25 max-[1050px]:gap-x-6.25 max-[1050px]:pl-7 max-[1050px]:pr-7 max-[850px]:grid-cols-1 max-[850px]:max-w-185 max-[540px]:pt-6.25 max-[540px]:pr-5 max-[540px]:pb-10 max-[540px]:pl-5">
        <aside className="min-w-0" aria-labelledby="expect-heading">
          <figure className="relative h-61.25 mt-0 mr-0 mb-7.5 ml-0 rounded-[13px] overflow-hidden bg-[#12314c] [&_img]:object-cover [&_img]:object-[center_52%] [&_figcaption]:absolute [&_figcaption]:bottom-0 [&_figcaption]:left-0 [&_figcaption]:right-0 [&_figcaption]:pt-8.75 [&_figcaption]:pr-5.5 [&_figcaption]:pb-5 [&_figcaption]:pl-5.5 [&_figcaption]:text-[#fff] [&_figcaption]:font-serif [&_figcaption]:text-[length:21px] [&_figcaption]:italic max-[850px]:h-80 max-[540px]:h-65 app-consultation-page-photo [&_figcaption]:[background-image:linear-gradient(transparent,_#001a32d9)]"><Image src="/images/about-consultation.png" alt="Illustration of financial professionals discussing a client's goals" fill sizes="(max-width: 850px) 100vw, 35vw" /><figcaption>Clarity starts with a conversation.</figcaption></figure>
          <div className="[&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h2]:text-[length:30px] [&_ol]:list-none [&_ol]:mt-6.25 [&_ol]:mr-0 [&_ol]:mb-6.25 [&_ol]:ml-0 [&_ol]:pt-0 [&_ol]:pr-0 [&_ol]:pb-0 [&_ol]:pl-0 [&_ol]:flex [&_ol]:flex-col [&_ol]:gap-y-6 [&_ol]:gap-x-6 [&_li]:flex [&_li]:gap-y-3.75 [&_li]:gap-x-3.75 [&_li_>_span]:grid [&_li_>_span]:place-items-center [&_li_>_span]:shrink-0 [&_li_>_span]:w-9.5 [&_li_>_span]:h-9.5 [&_li_>_span]:rounded-[50%] [&_li_>_span]:[border:1px_solid_#d2e4f7] [&_li_>_span]:bg-[#e9f2fc] [&_li_>_span]:text-[#0873c7] [&_li_>_span]:text-[length:13px] [&_li_>_span]:font-bold [&_h3]:mt-0 [&_h3]:mr-0 [&_h3]:mb-1.5 [&_h3]:ml-0 [&_h3]:text-[length:16px] [&_h3]:font-bold [&_li_p]:mt-0 [&_li_p]:mr-0 [&_li_p]:mb-0 [&_li_p]:ml-0 [&_li_p]:text-[#627287] [&_li_p]:text-[length:15px] [&_li_p]:leading-[1.6]"><p className="flex items-center gap-y-2.25 gap-x-2.25 mt-0 mr-0 mb-3.5 ml-0 text-[#3389c9] text-[length:11px] font-bold tracking-[.17em] leading-[1.5] uppercase app-consultation-page-eyebrow">A Simple Start</p><h2 id="expect-heading">What happens next?</h2><ol>{[{title:"Tell us what you need",text:"Share your goals and choose the service you’d like to discuss."},{title:"We connect with you",text:"Our team follows up using your preferred contact method to discuss availability."},{title:"Plan the way forward",text:"Together, we clarify your priorities and the next steps that fit your needs."}].map(({title,text},index)=><li key={title}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div>
          <div className="pt-5.5 pr-5.5 pb-5.5 pl-5.5 [border:1px_solid_#dce8f4] rounded-[10px] bg-[#eaf2fb] [&_h3]:text-[length:17px] [&_h3]:font-bold [&_h3]:mt-0 [&_h3]:mr-0 [&_h3]:mb-3.75 [&_h3]:ml-0 [&_a]:flex [&_a]:items-center [&_a]:gap-y-2.5 [&_a]:gap-x-2.5 [&_a]:text-[length:15px] [&_a]:mt-3 [&_svg]:text-[#0576d0] [&_p]:text-[length:12px] [&_p]:text-[#607690] [&_p]:mt-3.75 [&_p]:mr-0 [&_p]:mb-0 [&_p]:ml-0"><h3>Prefer to speak with us?</h3><a href="tel:+14372148299"><PhoneCall size={18} aria-hidden="true" />+1 (437) 214-8299</a><a href="mailto:info@rdpsc.ca"><Mail size={18} aria-hidden="true" />info@rdpsc.ca</a><p>Mon – Fri · 9:00 AM – 6:00 PM EST</p></div>
        </aside>
        <section className="min-w-0 pt-8.5 pr-8.5 pb-8.5 pl-8.5 [border:1px_solid_#e2ebf5] rounded-[14px] bg-[#fff] shadow-[0_12px_35px_#143b6508] [&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h2]:text-[length:clamp(29px,_2.8vw,_39px)] [&_h2]:leading-[1.15] max-[1050px]:pt-6.5 max-[1050px]:pr-6.5 max-[1050px]:pb-6.5 max-[1050px]:pl-6.5 max-[850px]:[grid-row:1] max-[540px]:pt-6.25 max-[540px]:pr-4.5 max-[540px]:pb-6.25 max-[540px]:pl-4.5 max-[540px]:[&_h2]:text-[length:30px]" aria-labelledby="consultation-form-heading"><p className="flex items-center gap-y-2.25 gap-x-2.25 mt-0 mr-0 mb-3.5 ml-0 text-[#3389c9] text-[length:11px] font-bold tracking-[.17em] leading-[1.5] uppercase app-consultation-page-eyebrow">Let’s Get to Know You</p><h2 id="consultation-form-heading">Request a Consultation</h2><p className="mt-3.5 mr-0 mb-7 ml-0 text-[length:15px] text-[#65768a] leading-[1.6] [&_span]:text-[#e01b38]">Tell us a little about yourself and how we can help. Fields marked <span>*</span> are required.</p><ConsultationForm /></section>
      </div>
    </main>
  );
}
