import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, BriefcaseBusiness, ChartNoAxesCombined, Download, FileText, Globe2, GraduationCap, Lightbulb, Link2, MessagesSquare, ShieldCheck, UsersRound } from "lucide-react";
import NewsletterForm from "@/components/footer/newsletter-form";

const topics = [
  { icon: FileText, title: "Tax Resources", description: "Guides, deadlines, and filing tips", href: "https://www.canada.ca/en/revenue-agency.html" },
  { icon: ChartNoAxesCombined, title: "Financial Planning", description: "Tools and insights for a secure future", href: "#resource-library" },
  { icon: ShieldCheck, title: "Insurance Guidance", description: "Understand your options", href: "https://www.clhia.ca/en-ca" },
  { icon: BriefcaseBusiness, title: "Business Resources", description: "Support for growth and compliance", href: "https://www.canada.ca/en/services/business.html" },
  { icon: GraduationCap, title: "Education & Mentorship", description: "Exam preparation and career support", href: "/services/professional-education-mentorship" },
  { icon: Globe2, title: "Payroll & Treasury", description: "Payroll, liquidity, and cash flow support", href: "/services/treasury-cash-flow" },
];
const insights = [
  { image: "/images/services/hero.png", alt: "Pen, calculator and financial documents", category: "Tax Tips", title: "Canadian Tax Filing Resources", description: "Find official filing information, forms, and guidance from the CRA.", href: "https://www.canada.ca/en/revenue-agency.html", action: "Visit CRA" },
  { image: "/images/resources/planning.png", alt: "Seedlings growing from increasing stacks of coins", category: "Financial Planning", title: "Plan a Stronger Financial Future", description: "A practical worksheet to organize your goals and questions.", href: "/resources/downloads/financial-planning-worksheet.pdf", action: "View Worksheet" },
  { image: "/images/resources/insurance.png", alt: "Paper family protected by a small umbrella", category: "Insurance", title: "Understanding Insurance in Canada", description: "Explore consumer information from Canada’s life and health insurance association.", href: "https://www.clhia.ca/en-ca", action: "Explore Resources" },
  { image: "/images/resources/training.png", alt: "Online workshop displayed on a laptop", category: "Training", title: "Professional Education & Mentorship", description: "Explore exam preparation, case writing, technical coaching, and one-on-one tutoring.", href: "/services/professional-education-mentorship", action: "Explore Mentorship" },
];
const downloads = [
  ["Tax Preparation Checklist for Individuals", "individual-tax-checklist.pdf"],
  ["Corporate Tax Preparation Checklist", "corporate-tax-checklist.pdf"],
  ["Financial Planning Worksheet", "financial-planning-worksheet.pdf"],
  ["Small Business Startup Worksheet", "business-startup-worksheet.pdf"],
  ["Segregated Funds: Questions to Ask", "segregated-funds-questions.pdf"],
];
const helpfulLinks = [
  ["Canada Revenue Agency (CRA)", "https://www.canada.ca/en/revenue-agency.html"],
  ["Financial Consumer Agency of Canada (FCAC)", "https://www.canada.ca/en/financial-consumer-agency.html"],
  ["CIRO — Investor Education", "https://www.ciro.ca/office-investor/guides-investors"],
  ["Canadian Life and Health Insurance Association", "https://www.clhia.ca/en-ca"],
  ["Business Development Bank of Canada (BDC)", "https://www.bdc.ca/en"],
  ["Government of Canada — Business Resources", "https://www.canada.ca/en/services/business.html"],
];

export default function ResourcesPage() {
  return (
    <main className="text-[#0b2341] font-body [&_h1]:font-serif [&_h1]:font-bold [&_h2]:font-serif [&_h2]:font-bold [&_h2]:text-[length:clamp(27px,_2.6vw,_38px)] [&_h2]:leading-[1.1] [&_h2]:tracking-[-.02em] [&_h2]:mt-0 [&_h2]:mr-0 [&_h2]:mb-0 [&_h2]:ml-0 [&_h3]:font-serif [&_h3]:font-bold [&_a:focus-visible]:[outline:3px_solid_#2090f6] [&_a:focus-visible]:outline-offset-[4px]">
      <section className="relative isolate bg-[#001e38] text-[#fff] overflow-hidden [&_h1]:text-[length:clamp(35px,_3.3vw,_52px)] [&_h1]:leading-[1.1] [&_h1]:tracking-[-.02em] [&_h1]:mt-0 [&_h1]:mr-0 [&_h1]:mb-0 [&_h1]:ml-0 [&_h1_span]:text-[#1ca3ef] max-[760px]:[&_h1]:text-[length:38px] max-[480px]:[&_h1]:text-[length:33px]" aria-labelledby="resources-heading">
        <Image src="/images/resources/hero.png" alt="Financial books and a mug on an office desk" fill sizes="100vw" preload className="z-[-2] object-cover object-center" />
        <div className="absolute z-[-1] top-0 right-[40%] bottom-0 left-0 max-[760px]:top-0 max-[760px]:right-0 max-[760px]:bottom-0 max-[760px]:left-0 app-resources-page-heroPanel [background-image:linear-gradient(110deg,_#001c37fc,_#00213bf0)] [clip-path:polygon(0_0,_82%_0,_100%_100%,_0_100%)] [@media(max-width:_760px)]:[clip-path:none] [@media(max-width:_760px)]:[background-image:linear-gradient(90deg,_#001b34f5,_#001b34dc_65%,_#001b3480)]" aria-hidden="true" />
        <div className="max-w-375 mt-auto mr-auto mb-auto ml-auto pt-7.5 pr-[clamp(24px,_4.7vw,_68px)] pb-7.5 pl-[clamp(24px,_4.7vw,_68px)] max-[760px]:pt-8.75 max-[760px]:pb-8.75 max-[480px]:pt-7 max-[480px]:pr-5 max-[480px]:pb-7 max-[480px]:pl-5">
          <nav className="flex gap-y-3 gap-x-3 mb-4.5 text-[#42b6f2] text-[length:15px]" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Resources</span></nav>
          <div className="w-[52%] max-w-177.5 [&_>_p]:text-[length:clamp(17px,_1.35vw,_20px)] [&_>_p]:leading-[1.55] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-0 [&_>_p]:ml-0 [&_>_p]:max-w-156.25 max-[760px]:w-[95%] max-[480px]:w-full"><h1 id="resources-heading">Resources for a<br />Brighter <span>Financial Future</span></h1><span className="block w-10.5 h-0.75 mt-4.25 mr-0 mb-4.25 ml-0 bg-[#ff183a] app-resources-page-redLine" aria-hidden="true" /><p>Helpful guides, tools, articles, and insights to support individuals, businesses, and organizations in making informed financial decisions.</p>
            <ul className="grid grid-cols-4 mt-6.25 mr-0 mb-0 ml-0 pt-0 pr-0 pb-0 pl-0 list-none max-w-145 [&_li]:flex [&_li]:flex-col [&_li]:items-center [&_li]:gap-y-2.25 [&_li]:gap-x-2.25 [&_li]:text-[length:16px] [&_li]:[border-right:1px_solid_#258bc6] [&_li:last-child]:[border:0] [&_svg]:text-[#21a6ee] [&_svg]:w-9.25 [&_svg]:h-9.25 max-[480px]:[&_li]:text-[length:13px] max-[480px]:[&_svg]:w-7.75 max-[480px]:[&_svg]:h-7.75">{[{ icon: BookOpen, label: "Learn" }, { icon: Lightbulb, label: "Grow" }, { icon: ChartNoAxesCombined, label: "Plan" }, { icon: UsersRound, label: "Succeed" }].map(({ icon: Icon, label }) => <li key={label}><Icon aria-hidden="true" /><span>{label}</span></li>)}</ul>
          </div>
        </div>
      </section>

      <div className="app-resources-page-content [background-image:linear-gradient(125deg,_#f3f9fd,_#f9fcff,_#f0f7fc)]">
        <section className="max-w-375 mt-auto mr-auto mb-auto ml-auto pt-7.5 pr-[clamp(24px,_4.7vw,_68px)] pb-7.5 pl-[clamp(24px,_4.7vw,_68px)] max-[480px]:pt-7 max-[480px]:pr-5 max-[480px]:pb-7 max-[480px]:pl-5 app-resources-page-container" aria-labelledby="topics-heading">
          <div className="flex justify-between items-center gap-y-10 gap-x-10 [&_>_p]:max-w-117.5 [&_>_p]:text-[length:15px] [&_>_p]:leading-[1.5] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-3 [&_>_p]:ml-0 max-[760px]:items-start max-[760px]:flex-col max-[760px]:gap-y-0 max-[760px]:gap-x-0 max-[760px]:[&_>_p]:mt-0 max-[760px]:[&_>_p]:mr-0 max-[760px]:[&_>_p]:mb-5 max-[760px]:[&_>_p]:ml-0 app-resources-page-sectionHeader"><div><p className="mt-0 mr-0 mb-2.5 ml-0 text-[length:11px] leading-[1.5] font-bold tracking-[.24em] uppercase">Explore by Topic</p><h2 id="topics-heading">Find the Resources You Need</h2><span className="block w-10.5 h-0.75 mt-4.25 mr-0 mb-4.25 ml-0 bg-[#ff183a] app-resources-page-redLine" aria-hidden="true" /></div><p>Browse our resources by category to quickly find the information that’s most relevant to you.</p></div>
          <div className="grid grid-cols-6 gap-y-3.5 gap-x-3.5 max-[1100px]:grid-cols-3 max-[480px]:grid-cols-2 max-[480px]:gap-y-3 max-[480px]:gap-x-3">{topics.map(({ icon: Icon, title, description, href }) => <Link key={title} href={href} className="flex flex-col items-center pt-5 pr-3 pb-4.5 pl-3 rounded-[8px] bg-[#fff] shadow-[0_6px_18px_#12385906] text-center [transition:box-shadow_160ms_ease,_transform_160ms_ease] hover:[transform:translateY(-3px)] hover:shadow-[0_9px_22px_#12385915] [&_h3]:mt-3.25 [&_h3]:mr-0 [&_h3]:mb-2.25 [&_h3]:ml-0 [&_h3]:text-[length:18px] [&_h3]:leading-[1.2] [&_h3]:tracking-[-.025em] [&_p]:mt-0 [&_p]:mr-0 [&_p]:mb-3.75 [&_p]:ml-0 [&_p]:text-[length:15px] [&_p]:leading-[1.5] [&_p]:max-w-41.25 max-[760px]:[&_h3]:text-[length:17px] max-[760px]:[&_p]:text-[length:14px] max-[480px]:pt-4.5 max-[480px]:pr-3 max-[480px]:pb-4.5 max-[480px]:pl-3 motion-reduce:[transition:none]" {...(href.startsWith("https:") ? { target: "_blank", rel: "noopener noreferrer" } : {})}><span className="grid place-items-center w-16.25 h-16.25 rounded-[50%] bg-[#eff6ff] text-[#006fe3] [&_svg]:w-9 [&_svg]:h-9 [&_svg]:[stroke-width:1.7]"><Icon aria-hidden="true" /></span><h3>{title}</h3><p>{description}</p><ArrowRight size={19} className="text-[#006deb] mt-auto" aria-hidden="true" /></Link>)}</div>
        </section>

        <section className="max-w-375 mt-auto mr-auto mb-auto ml-auto pt-7.5 pr-[clamp(24px,_4.7vw,_68px)] pb-7.5 pl-[clamp(24px,_4.7vw,_68px)] max-[480px]:pt-7 max-[480px]:pr-5 max-[480px]:pb-7 max-[480px]:pl-5 app-resources-page-container  pt-0 max-[480px]:pt-0 app-resources-page-insightsSection [@media(max-width:_760px)]:[&_.app-resources-page-sectionHeader_>_a]:[margin-bottom:20px]" aria-labelledby="insights-heading">
          <div className="flex justify-between items-center gap-y-10 gap-x-10 [&_>_p]:max-w-117.5 [&_>_p]:text-[length:15px] [&_>_p]:leading-[1.5] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-3 [&_>_p]:ml-0 max-[760px]:items-start max-[760px]:flex-col max-[760px]:gap-y-0 max-[760px]:gap-x-0 max-[760px]:[&_>_p]:mt-0 max-[760px]:[&_>_p]:mr-0 max-[760px]:[&_>_p]:mb-5 max-[760px]:[&_>_p]:ml-0 app-resources-page-sectionHeader"><div><p className="mt-0 mr-0 mb-2.5 ml-0 text-[length:11px] leading-[1.5] font-bold tracking-[.24em] uppercase">Featured Resources</p><h2 id="insights-heading">Latest Insights</h2><span className="block w-10.5 h-0.75 mt-4.25 mr-0 mb-4.25 ml-0 bg-[#ff183a] app-resources-page-redLine" aria-hidden="true" /></div><Link className="inline-flex items-center gap-y-1.5 gap-x-1.5 text-[#006bee] text-[length:15px] leading-[1.4] hover:underline hover:[text-underline-offset:4px] app-resources-page-textLink" href="#resource-library">View Resource Library <ArrowRight size={17} aria-hidden="true" /></Link></div>
          <div className="grid grid-cols-4 gap-y-5.5 gap-x-5.5 max-[1100px]:gap-y-4 max-[1100px]:gap-x-4 max-[760px]:grid-cols-2 max-[480px]:grid-cols-1 max-[480px]:gap-y-5 max-[480px]:gap-x-5">{insights.map(({ image, alt, category, title, description, href, action }) => <article className="flex flex-col min-w-0 overflow-hidden rounded-[8px] bg-[#fff] shadow-[0_5px_13px_#16457008]" key={title}><div className="relative aspect-[2.55] [&_img]:object-cover max-[480px]:aspect-[2.1]"><Image src={image} alt={alt} fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 25vw" /></div><div className="flex flex-col items-start flex-1 pt-4 pr-5 pb-5.5 pl-5 [&_h3]:text-[length:21px] [&_h3]:leading-[1.2] [&_h3]:mt-3 [&_h3]:mr-0 [&_h3]:mb-2.25 [&_h3]:ml-0 [&_h3]:tracking-[-.02em] [&_p]:mt-0 [&_p]:mr-0 [&_p]:mb-3.75 [&_p]:ml-0 [&_p]:text-[length:16px] [&_p]:leading-[1.4] [&_p]:text-[#40516b] max-[1100px]:pl-3.75 max-[1100px]:pr-3.75 max-[1100px]:[&_h3]:text-[length:19px] max-[1100px]:[&_p]:text-[length:15px] max-[480px]:pt-5 max-[480px]:pr-5 max-[480px]:pb-5 max-[480px]:pl-5 max-[480px]:[&_h3]:text-[length:23px] app-resources-page-insightBody [&_.app-resources-page-textLink]:[margin-top:auto]"><span className="pt-1 pr-2.25 pb-1 pl-2.25 rounded-[6px] bg-[#eaf3ff] text-[#0065d6] text-[length:10px] font-bold tracking-[.07em] uppercase">{category}</span><h3>{title}</h3><p>{description}</p><Link className="inline-flex items-center gap-y-1.5 gap-x-1.5 text-[#006bee] text-[length:15px] leading-[1.4] hover:underline hover:[text-underline-offset:4px] app-resources-page-textLink" href={href} {...(href.startsWith("https:") ? { target: "_blank", rel: "noopener noreferrer" } : {})}>{action} <ArrowRight size={16} aria-hidden="true" /></Link></div></article>)}</div>
        </section>

        <section className="max-w-375 mt-auto mr-auto mb-auto ml-auto pt-7.5 pr-[clamp(24px,_4.7vw,_68px)] pb-7.5 pl-[clamp(24px,_4.7vw,_68px)] max-[480px]:pt-7 max-[480px]:pr-5 max-[480px]:pb-7 max-[480px]:pl-5 app-resources-page-container  grid grid-cols-[1.15fr_1.2fr_.9fr] gap-y-7.5 gap-x-7.5 pt-1.25 pb-9.5 max-[1100px]:grid-cols-[1fr_1fr] max-[1100px]:gap-y-5.5 max-[1100px]:gap-x-5.5 max-[760px]:grid-cols-1 max-[480px]:pt-0" aria-label="Downloads, helpful links and support">
          <div id="resource-library" className="min-w-0 scroll-mt-28.75 [&_h2]:text-[length:clamp(25px,_2.25vw,_32px)] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-4 [&_>_p]:ml-0 [&_>_p]:text-[length:14px] [&_>_p]:leading-[1.4] app-resources-page-library [&_.app-resources-page-redLine]:[margin:10px_0]"><h2>Resource Library</h2><span className="block w-10.5 h-0.75 mt-4.25 mr-0 mb-4.25 ml-0 bg-[#ff183a] app-resources-page-redLine" aria-hidden="true" /><p>Download preparation checklists and planning worksheets.</p><ul className="flex flex-col gap-y-1.75 gap-x-1.75 pt-0 pr-0 pb-0 pl-0 mt-0 mr-0 mb-0 ml-0 list-none [&_a]:flex [&_a]:items-center [&_a]:gap-y-3 [&_a]:gap-x-3 [&_a]:min-h-11 [&_a]:pt-2.5 [&_a]:pr-3 [&_a]:pb-2.5 [&_a]:pl-3 [&_a]:rounded-[5px] [&_a]:bg-[#fff] [&_a]:shadow-[0_3px_10px_#183f6807] [&_a]:text-[length:13px] [&_a]:leading-[1.35] [&_a:hover]:bg-[#edf5ff] [&_svg]:w-4.5 [&_svg]:h-4.5 [&_svg]:text-[#006bff] [&_svg]:shrink-0 [&_svg:last-child]:ml-auto [&_svg:last-child]:w-4 app-resources-page-resourceList [&_.app-resources-page-pdfIcon]:[color:#ff183c]">{downloads.map(([title, file]) => <li key={file}><a href={`/resources/downloads/${file}`} download aria-label={`Download ${title} (PDF)`}><FileText className="app-resources-page-pdfIcon" aria-hidden="true" /><span>{title}</span><Download aria-hidden="true" /></a></li>)}</ul></div>
          <div id="helpful-links" className="min-w-0 scroll-mt-28.75 [&_h2]:text-[length:clamp(25px,_2.25vw,_32px)] [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-4 [&_>_p]:ml-0 [&_>_p]:text-[length:14px] [&_>_p]:leading-[1.4] app-resources-page-library [&_.app-resources-page-redLine]:[margin:10px_0]"><h2>Helpful Links</h2><span className="block w-10.5 h-0.75 mt-4.25 mr-0 mb-4.25 ml-0 bg-[#ff183a] app-resources-page-redLine" aria-hidden="true" /><p>Quick access to useful tools and external resources.</p><ul className="flex flex-col gap-y-1.75 gap-x-1.75 pt-0 pr-0 pb-0 pl-0 mt-0 mr-0 mb-0 ml-0 list-none [&_a]:flex [&_a]:items-center [&_a]:gap-y-3 [&_a]:gap-x-3 [&_a]:min-h-11 [&_a]:pt-2.5 [&_a]:pr-3 [&_a]:pb-2.5 [&_a]:pl-3 [&_a]:rounded-[5px] [&_a]:bg-[#fff] [&_a]:shadow-[0_3px_10px_#183f6807] [&_a]:text-[length:13px] [&_a]:leading-[1.35] [&_a:hover]:bg-[#edf5ff] [&_svg]:w-4.5 [&_svg]:h-4.5 [&_svg]:text-[#006bff] [&_svg]:shrink-0 [&_svg:last-child]:ml-auto [&_svg:last-child]:w-4 app-resources-page-resourceList [&_.app-resources-page-pdfIcon]:[color:#ff183c]">{helpfulLinks.map(([title, href]) => <li key={href}><a href={href} target="_blank" rel="noopener noreferrer"><Link2 aria-hidden="true" /><span>{title}</span><ArrowRight aria-hidden="true" /></a></li>)}</ul></div>
          <aside className="[&_h2]:text-[length:clamp(25px,_2.25vw,_32px)] relative isolate overflow-hidden rounded-[9px] pt-6.5 pr-6.5 pb-6.5 pl-6.5 [&_>_p]:mt-0 [&_>_p]:mr-0 [&_>_p]:mb-5.5 [&_>_p]:ml-0 [&_>_p]:text-[length:15px] [&_>_p]:leading-[1.5] max-[1100px]:[grid-column:1_/_-1] app-resources-page-questionCard [background-image:linear-gradient(120deg,_#eaf4ff,_#f4f8ff)]"><MessagesSquare className="absolute z-[-1] bottom-5 right-1.5 w-36.25 h-36.25 text-[#cde3fd] [stroke-width:1.4]" aria-hidden="true" /><h2>Have a Question?</h2><span className="block w-10.5 h-0.75 mt-4.25 mr-0 mb-4.25 ml-0 bg-[#ff183a] app-resources-page-redLine" aria-hidden="true" /><p>Check our FAQs or reach out to our team for more information.</p><Link href="/services#faqs" className="flex items-center justify-center gap-y-2 gap-x-2 w-fit min-h-10.75 pt-3 pr-5.75 pb-3 pl-5.75 rounded-[5px] [border:1px_solid_#006ff0] text-[length:14px] text-[#fff] bg-[#006bd9] mb-3">View FAQs <ArrowRight size={16} aria-hidden="true" /></Link><Link href="/#contact" className="flex items-center justify-center gap-y-2 gap-x-2 w-fit min-h-10.75 pt-3 pr-5.75 pb-3 pl-5.75 rounded-[5px] [border:1px_solid_#006ff0] text-[length:14px] text-[#006ade] bg-[#ffffff70]">Contact Us <ArrowRight size={16} aria-hidden="true" /></Link></aside>
        </section>
      </div>

      
    </main>
  );
}
